### ISSUE TITLE
Colors are not showing properly

### ISSUE THREAD

**Issue by alberto-coolshop** [ggordan/GutterColor#100]
HI Guys, 
I've just installed colorGutter
I'm on Linux - Ubuntu 14.04
Sublime text 3 build 3103

But colors are shown this way:
![image](https://cloud.githubusercontent.com/assets/13332592/14639705/4feb59f8-063e-11e6-9e52-13189014634b.png)

Nothing was logged into console...
Hope it helps...

**Comment by ThomasBck** [comment]
Hi, I've got exactly the same issue.... 
on OSX 10.11.4.
please help

**Comment by ThomasBck** [comment]
Very strange... I remove the package, restart ST and without  the plugin the dot appears...I think something went wrong.

**Comment by ronanjia** [comment]
this  is the placeholder image of sublime mostly when sublime cannot find right position for "convert", try below and it helped me, mine is "10.11.3"( or you can type "which convert" in terminal to get path of "convert")

"convert_path" : "/opt/local/bin/convert",

**Comment by Dantevg** [comment]
@ronanjia How do I do that thing with
> "convert_path" : "/opt/local/bin/convert",

Yes, I know this issue is old.

**Comment by ronanjia** [comment]
@Dantevg  sorry i just noticed, open "package settings" from the menu, find "GutterColor" package and open it's "User Setting" file, then put that code in the file =)

**Comment by Dantevg** [comment]
@ronanjia Ah thank you. I only don't need it anymore, but I could have known.

**Comment by alberto-coolshop** [comment]
Closing due to time
