### ISSUE TITLE
Gutter colour error

### ISSUE THREAD

**Issue by Francisc** [ggordan/GutterColor#17]
Hello,

This is what I see on ST3-latest,  Windows7x64 and ImageMagick-6.8.8-8-Q16-x64-dll.

![ss](https://f.cloud.github.com/assets/699657/2414688/f11ca2be-aaec-11e3-8af7-b4a76c9dd7cb.jpg)

Any idea what's up?

**Comment by mariomga** [comment]
hello, I had the same problem, it helped me to use: "convert.exe" only instead of "/usr/local/bin/convert". It really helps to verify the path where the program was installed as it is mentioned in this article (http://wesbos.com/css-gutter-color-sublime-text/#comment-106667). Also go ahead and open a command window to verify if it runs ( win+R > "cmd" > convert.exe), if it runs you are going good but if it fails reinstall again with another version as I did, I have used: ImageMagick-7.0.4-6-Q16-HDRI-x86-dll. At the end It should be as fallow:

{
 "convert_path" : "convert.exe"
}

**Comment by uwjiaoxing** [comment]
Need to restart sublime

**Comment by dirkakrid** [comment]
### A big thanks to the post by `webconsult` !

**_Exactly_** the same issue on Windows 7

Win 7 x64, ST3, and latest ImageMagick release ImageMagick-7.0.5-4-Q16-x64-dll.exe

I'm running, scratch that, Was Running the `Flatland Monokai` theme. The moment I changed it to `Flatland Dark` instantly the the colored image icons were generated.

I had started to debug the package scripts to work out what was going wrong, and found this post.

Also, during the Windows setup there is an option to add ImageMagick in the system path. If this is selected, there is no need to define the `convert_path` variable.

( On a Windows platform a python script in the package will grab the Windows OS Path, split it to directory locations, and then automatically appends `convert.exe` to each path, recursively looking for a file match. )

Thanks for the extension, works great !

**Comment by robert-coleman** [comment]
On Windows: Use the full path in your config file "convert_path" : "C:/Program Files/ImageMagick-7.0.7-Q16/convert.exe". If you can't see convert.exe, try reinstalling ImageMagick and ticking the "legacy" box which will install convert.exe for you (just read through the installer slowly this time). By default they don't include that EXE anymore.

**Comment by nomodule** [comment]
Goto "C:\Program Files\ImageMagick-7.0.7-Q16" or wherever you have installed it according to your OS and version of imagemagick and then rename "magick.exe" to "convert.exe".

**Comment by paulietheboss** [comment]
> On Windows: Use the full path in your config file "convert_path" : "C:/Program Files/ImageMagick-7.0.7-Q16/convert.exe". If you can't see convert.exe, try reinstalling ImageMagick and ticking the "legacy" box which will install convert.exe for you (just read through the installer slowly this time). By default they don't include that EXE anymore.

This fixed it for me. Cheers!

**Comment by xillegas** [comment]
> > On Windows: Use the full path in your config file "convert_path" : "C:/Program Files/ImageMagick-7.0.7-Q16/convert.exe". If you can't see convert.exe, try reinstalling ImageMagick and ticking the "legacy" box which will install convert.exe for you (just read through the installer slowly this time). By default they don't include that EXE anymore.
> 
> This fixed it for me. Cheers!

This work for me too, reinstal with legacy box, and that path, but **I must to erase** ".exe" in the path and it works! 
My complete path was `"convert_path" : "C:/Program Files/ImageMagick-7.1.0-Q16-HDRI/convert" `
Thank you very much.
