### ISSUE TITLE
Black dots & Unable to decode on ST3 / Mac

### ISSUE THREAD

**Issue by fabianmu** [ggordan/GutterColor#19]
The plugin shows black dots and "Unable to decode" messages in the ST console. See image for details.

![screen shot 2014-03-14 at 12 11 15](https://f.cloud.github.com/assets/89517/2420066/88c97390-ab69-11e3-8ec0-b6fdffbbc6a8.png)

**Comment by isaacalves** [comment]
@knightq 
thank you. got that problem again, on Yosemite now, and that solved.

**Comment by luis3dms** [comment]
Reinstalling as @KNIGHTQ commented, and run also `Brew list ImageMagick` and look for the "convert". In my case: "/usr/local/Cellar/imagemagick/7.0.5-9/bin/convert"

Before
{
“convert_path” : “/usr/local/bin/convert”
}
Now:
{
“convert_path” : “/usr/local/Cellar/imagemagick/7.0.5-9/bin/convert”
}

I hope this works!
