### ISSUE TITLE
All colours showing the same colour blob

### ISSUE THREAD

**Issue by realmikebutler** [ggordan/GutterColor#6]
for me It's showing the same odd colour blob for every colour.  See the attached screenshot…

I'm using Sublime Text Build 3059

![screenshot 2014-02-23 15 12 14](https://f.cloud.github.com/assets/176980/2240601/b6d5d164-9c9d-11e3-8bc7-2d930771dc38.png)

**Comment by deweyaccounts** [comment]
I was having the problem with the red/orange squares and finally figured it out today by inspecting my console.app, not the sublime text console (which doesn't provide enough detail). I saw this log under **User Diagnostics and Reports** :
```
Dyld Error Message:
  Library not loaded: /usr/local/lib/libpng16.16.dylib
  Referenced from: /usr/local/lib/libfreetype.6.dylib
  Reason: Incompatible library version: libfreetype.6.dylib requires version 33.0.0 or later, but libpng16.16.dylib provides version 29.0.0
```
So I went to my command line and did a brew update and uninstalled libpng. I ended up updating from libpng 1.6.12 to 1.6.17. I'm happy to report that this solution fixed the problem for me.

**Comment by vl4dt** [comment]
I was having the exact same issue @realmikebutler reported, I'm on OS X Yosemite.
This worked for me:
https://packagecontrol.io/packages/Gutter%20Color

...

Fixing ImageMagick on OSX

If you're experiencing issues with ImageMagick (installed via brew) when using GutterColor on OSX, follow these instructions to fix it.

* Uninstall IM with brew uninstall imagemagick
* Install again with a couple of options brew install imagemagick --with-xz --with-font-config --with-little-cms --with-little-cms2
* Check the location of convert with type convert
* Copy the location and edit the GutterColor/Settings - User convert_path to be the value of step 3.

...

In my particular case the 'convert' path I used was:
__/opt/ImageMagick/bin/convert__

And problem solved

**Comment by padhie** [comment]
I have the same Problem like realmikebutler at the beginning :(
I use:
- Sublime Text 3
- Windows 7 64 bit
- ImageMagig 7.0.3-8-Q16-x64

pleace help me :'(

**Comment by JonasPY** [comment]
El problema viene por que la version de ImageMagick 7, ya no usa Convert y ahora se llama Magick

la linea de codigo a cambiar dentro del archivo line.py es : 

![image](https://user-images.githubusercontent.com/7065732/34630426-09342dd4-f23a-11e7-83e1-a289d521dac8.png)


luego de hacer esto limpiar la cache de gutter, y todo ok.
