### ISSUE TITLE
Afterglow theme + color scheme results in orange stripes instead of GutterColor

### ISSUE THREAD

**Issue by nivshah** [ggordan/GutterColor#80]
I tried fixing the current color scheme and clearing cache, as well as restarting a few times.

https://www.dropbox.com/s/o4fqc0d7b4ypvl9/Screenshot%202015-03-11%2007.49.56.png?dl=0

I'm open to the idea that this is a bug in Afterglow (http://yabatadesign.github.io/afterglow-theme/ & https://github.com/YabataDesign/afterglow-theme) and I'll open a related issue there.

**Comment by nivshah** [comment]
https://github.com/YabataDesign/afterglow-theme/issues/36

**Comment by jbrooksuk** [comment]
Does GutterColor work for you under a different colour scheme?

**Comment by nivshah** [comment]
I had Soda Dark working fine yesterday, and installed Afterglow and ran into this issue.

**Comment by nivshah** [comment]
I actually have GutterColor working OK with afterglow on another system, so I think this is going to require more debugging on my end.

**Comment by jbrooksuk** [comment]
Make sure you have Imagemagick installed.
