### ISSUE TITLE
Color is using named colors from sass variables instead of hex or rgb.

### ISSUE THREAD

**Issue by HagadoneDigital** [ggordan/GutterColor#90]
For example: $tiffany-blue: #0fc4b1;
Gutter Color is rendering a basic blue color when in fact the hex is a shade of green.

This is happening on all my sass variables.

**Comment by mp3wizard** [comment]
+1 Please specific name color detection only color name such as
http://www.w3schools.com/cssref/css_colornames.asp

or

http://xkcd.com/color/rgb/ (JSON file can download from https://github.com/zeplin/zeplin-palette )

**Comment by jbrooksuk** [comment]
I'll have a fix ready soon.

**Comment by jbrooksuk** [comment]
Done.

**Comment by jbrooksuk** [comment]
https://github.com/ggordan/GutterColor/releases/tag/v0.3.3
