### ISSUE TITLE
in less, class name would cover the real color.

### ISSUE THREAD

**Issue by KyleBing** [ggordan/GutterColor#94]
![screen2015_1101_1029](https://cloud.githubusercontent.com/assets/12215982/10866935/7b9a811e-8083-11e5-91bf-fb6ed5ea333b.jpg)

**Comment by hippogriffic** [comment]
This is also happening with Sass variables. Any variables that include names of web colors produce dots that mach the color names over the hex codes. Is there a setting to turn off the use of web color names?
![image](https://cloud.githubusercontent.com/assets/9528348/10936577/60a11f1c-82e5-11e5-9dea-ffc47befedc8.png)

**Comment by jeffmckeand** [comment]
Same here w/ Sass. HTML/CSS color names trump defined hex values if they appear on the same line. Please fix.

**Comment by 315568099** [comment]
已收到你的邮件~ 谢谢
